name: Build workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build job
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Set up step
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Build
      run: |
        python build.py
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m "Updated output"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
